spring:
  application:
    name: Com-Service
  mail:
    host: ${mail.host}
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  telegram:
    username: ${telegram.username}
    token: ${telegram.token}


#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

logging:
  level:
    org.springframework.cloud: debug


    org:
      springframework:
        kafka=DEBUG: