spring:
  application:
    name: Com-Service
  mail:
    host: mail.abinet.dev
    port: 587
    username: askuala@abinet.dev
    password: FPFzjDbzFwUKh9DjYP79
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  telegram:
    username: BookTestTrialBot
    token: 6425742378:AAHACiqd2rjvTxJ0HBSrl7hf_s7yVMgih4Q


#Service Discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

logging:
  level:
    org.springframework.cloud: debug


    org:
      springframework:
        kafka=DEBUG: